### ISSUE TITLE
TypeError: modules.map is not a function

### ISSUE THREAD

**Issue by pipsie100** [eastuto/my-blog-01#14]
$ next dev
ready - started server on http://localhost:3000
TypeError: modules.map is not a function
    at generateIncludes (C:\Projects\Reason_Ocaml\next\node_modules\next-transpile-modules\src\next-transpile-modules.js:22:28)
    at withTM (C:\Projects\Reason_Ocaml\next\node_modules\next-transpile-modules\src\next-transpile-modules.js:48:22)
    at normalizeConfig (C:\Projects\Reason_Ocaml\next\my-blog\node_modules\next\dist\next-server\server\config.js:5:2023)
    at loadConfig (C:\Projects\Reason_Ocaml\next\my-blog\node_modules\next\dist\next-server\server\config.js:6:147) 
    at new Server (C:\Projects\Reason_Ocaml\next\my-blog\node_modules\next\dist\next-server\server\next-server.js:1:3667)
    at new DevServer (C:\Projects\Reason_Ocaml\next\my-blog\node_modules\next\dist\server\next-dev-server.js:1:2922)    at createServer (C:\Projects\Reason_Ocaml\next\my-blog\node_modules\next\dist\server\next.js:2:300)
    at start (C:\Projects\Reason_Ocaml\next\my-blog\node_modules\next\dist\server\lib\start-server.js:1:385)        
    at nextDev (C:\Projects\Reason_Ocaml\next\my-blog\node_modules\next\dist\cli\next-dev.js:21:279)
    at commands.(anonymous function).then.exec (C:\Projects\Reason_Ocaml\next\my-blog\node_modules\next\dist\bin\next:28:341)
error Command failed with exit code 1.

**Comment by suzdalnitski** [comment]
It seems that the `next.config.js` file is outdated.

Here's a working version:
```js
const withTM = require("next-transpile-modules")(["bs-platform"]);

module.exports = withTM({
  pageExtensions: ["jsx", "js", "bs.js"]
});
```
